cc_library(
    name = "TAppCommon",
    srcs = ["program_options_lite.cpp"],
    hdrs = ["program_options_lite.h"],
	copts = ["-Itensorflow/HM16P001A/Lib"],
    visibility = ["//visibility:public"],
)
