# Description:
#   Tensorflow C++ inference example for labeling images.

visibility = ["//visibility:public"],

#licenses(["notice"])  # Apache 2.0

#exports_files(["LICENSE"])


cc_library(
    name = "TIMETEST",
    srcs = ["TimeTest.cpp"],
	hdrs = ["TimeTest.h"],
	copts = ["-Itensorflow/HM16P001A/Lib/TIME/"],
	visibility = ["//visibility:public"],
)


